import type { Metadata } from "next";
import { Inter } from "next/font/google";
import WrapperProvider from "@/context/WrapperProvider";
import { headers } from "next/headers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const headersList = headers();
  const pathname = headersList.get("x-invoke-path") || "";
  return (
    <html lang="en">
      <body
        className={inter.className}
        suppressHydrationWarning={true}
        style={
          pathname === "/login" || pathname === "/register"
            ? { overflow: "hidden" }
            : {}
        }
      >
        <WrapperProvider>
          {children}
        </WrapperProvider>
      </body>
    </html>
  );
}
